// Copyright 2009 Google Inc. All Rights Reserved.

/**
 * AIDL for callbacks from the TTS Service
 * ITTSUserCallback.java is autogenerated from this
 *
 * @author sdoyon@google.com (Stephane Doyon)
 */

package com.google.tts;

/**
 * Callback on completing an utterance.
 * A one-way interface so the server does not block waiting for the client.
 */
oneway interface ITTSUserCallback {
  void onCompletion(boolean interrupted, int caller_arg);
}
